### ISSUE TITLE
Don't understand the plugin 😅

### ISSUE THREAD

**Issue by marcelmanz** [hrsh7th/nvim-automa#1]
Hi, I would like to test this because as far as I understood, what I can do with `nvim-automa` is to have a list of personal macros and then use them with the `.` command in some way. What I do not understand is how can I activate them.

For example if I create the macro:
```lua
{ 'n', 'I- **<Esc>A**<Esc>j' },
```

Then I could surround automatically lines of text with `***` on each side, right? 

And other questions:
- How can I run the macros once I already declared them? 
- And what is the `n#`?

**Comment by marcelmanz** [comment]
You created this 1h ago sorry, I just checked the commits now.

**Comment by hrsh7th** [comment]
Please forgive me for not being good at English...

First, let's start with the settings below.

```lua
require('automa').setup {
   mapping = {
     ['.'] = {
       { '!n(h,j,k,l)+' }
     }
   }
}
````

The above setting is to repeat the sequence of keys that do not match `n(h,j,k,l)` using the `.` key.

You can see the nvim-automa's internal key-sequence via `:AutomaToggleDebugger`.

nvim-automa extracts from a list of keys that is suitable for repeating the most recent occurrence of `!n(h,j,k.l)+`.

**Comment by hrsh7th** [comment]
The `n#` means `match one-key in normal-mode that modified the buffer`.

`#` means `match only keys that modified the buffer`.

**Comment by hrsh7th** [comment]
I think I will eventually make some breaking changes to the query grammer.
However, at the moment, this is what it means.

**Comment by hrsh7th** [comment]
- `n`
    - match any key in normal-mode
- `n*`
    - match at-least zero keys in normal-mode
- `n+`
    - match at-least one keys in normal-mode
- `n(h,j,k,l)`
    - match `h,j,k.l` key in normal-mode
- `n(h,j,k,l)#`
    - match `h,j,k.l` key in normal-mode that modified the buffer.
- `!n(h,j,k,l)`
    - negate version of `n(h,j,k,l)`
    - `!` applied only `mode` and `chars` (`*,+,#` is not negated)
